### ISSUE TITLE
does not build on ghc 8.2

### ISSUE THREAD

**Issue by accursoft** [seereason/harp#1]
https://github.com/seereason/harp/blob/2539d249480b2ac9a6d9a77bb5d478b02bfb6eef/harp.cabal#L30

**Comment by ddssff** [comment]
Does it build if this dependency is changed?

**Comment by ddssff** [comment]
I guess there's no harm in changing if - only affects 8.2 users and if there's a problem someone will report it.

**Comment by ddssff** [comment]
Pushed.

**Comment by accursoft** [comment]
Hackage?

**Comment by ddssff** [comment]
Huh, did not realize I was maintainer - I don't even know what this package is!  But happy to upload.
